server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1

        - id: api-docs-patient-route
          uri: http://patient-serive:4000
          predicates:
            - Path=/api-docs/patient/
          filters:
            - RewritePth=/api-docs/patient/, /v3/api-docs

