### POST request to create a patient
POST http://lb-8aa33665.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "name": "Doe Johnwithbilling&kafka2",
  "email": "Xedddxxffe545d@gmail.com",
  "address": "123 viola lane",
  "dateOfBirth": "2000-12-09",
  "registeredDate": "2025-11-05"
}

###